import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const web=path.join(root,'web');
const manifest=JSON.parse(fs.readFileSync(path.join(web,'animation-lab-manifest.json'),'utf8'));
assert.equal(manifest.version,8,'Animation Lab manifest must use the clean-room motion contract');
assert.equal(manifest.demos.length,33,'All thirty-three product patterns must be present');
assert.equal(new Set(manifest.demos.map(item=>item.id)).size,manifest.demos.length,'Demo ids must be unique');
for(const demo of manifest.demos){
  const source=fs.readFileSync(path.join(web,demo.file),'utf8');
  assert.match(source,/prefers-reduced-motion|reduce/,'Reduced motion path is required: '+demo.file);
  assert.match(source,/URLSearchParams/,'Query harness is required: '+demo.file);
  assert.match(source,/window\.__ready=true/,'Deterministic browser readiness is required: '+demo.file);
  assert.match(source,/viewport/,'Responsive viewport is required: '+demo.file);
  assert.doesNotMatch(source,/<script\s+src=/i,'Remote scripts are forbidden: '+demo.file);
  assert.doesNotMatch(source,/\beval\s*\(|document\.write/i,'Unsafe execution is forbidden: '+demo.file);
  assert.doesNotMatch(source,/https?:\/\//i,'Standalone demos must not call remote origins: '+demo.file);
  assert.match(source,/id="crisp-motion-contract"/,'Crisp motion stylesheet is required: '+demo.file);
  assert.match(source,/font-family:Manrope/,'Local Cyrillic display font is required: '+demo.file);
  assert.equal((source.match(/data:font\/woff2;base64,/g)||[]).length,4,'All four local font subsets must be embedded for the sandbox: '+demo.file);
  assert.doesNotMatch(source,/backdrop-filter:\s*blur/i,'Optical backdrop blur is forbidden: '+demo.file);
  assert.doesNotMatch(source,/filter:\s*blur/i,'Raster blur is forbidden: '+demo.file);
  assert.doesNotMatch(source,/box-shadow:|boxShadow/i,'Blurred shadows are forbidden: '+demo.file);
  assert.doesNotMatch(source,/filter:\s*grayscale/i,'Muted states must stay crisp: '+demo.file);
  assert.match(source,/rel="icon" href="data:,"/i,'Standalone demos must not request a missing favicon: '+demo.file);
  assert.match(source,/body \*\{font-family:Manrope[^}]*!important/,'All visible text must resolve to the local font: '+demo.file);
  assert.doesNotMatch(source,/(?:const|let|var)\s+\w+\s*=\s*Number\([^\n;]*\.get\(["']t["']\)\)/,'Missing t must not become frozen frame zero: '+demo.file);
}
const vault=fs.readFileSync(path.join(web,'animation-vault-dial.html'),'utf8');
assert.match(vault,/rotateY\(-72deg\)/,'Vault door must open through a bounded 3D rotation');
assert.match(vault,/pointerdown|pointermove/,'Vault dial must support direct manipulation');
assert.match(vault,/addEventListener\("wheel"/,'Vault dial must support wheel input');
assert.match(vault,/ArrowRight|ArrowLeft/,'Vault dial must support keyboard rotation');
assert.match(vault,/prefers-reduced-motion:reduce/,'Vault must provide a reduced-motion presentation');
assert.doesNotMatch(vault,/class="chamber"[^>]*aria-hidden/,'Interactive vault chamber must stay in the accessibility tree');
assert.match(vault,/replace\(\/\\D\/g,""\)/,'Vault code input must reject non-numeric characters');
assert.match(vault,/window\.__ready=true/,'Vault must expose deterministic browser readiness');
assert.match(vault,/overflow:clip/,'Vault shell must clip decorative depth layers to the card boundary');
assert.match(vault,/calc\(100dvh - 250px\)/,'Vault chamber must size from available viewport height');
assert.match(vault,/\.controls>\*\{min-width:0\}/,'Vault controls must be shrink-safe inside the card');
const guardian=fs.readFileSync(path.join(web,'animation-reactive-login.html'),'utf8');
assert.match(guardian,/Eclipse crisp motion contract/,'Guardian form must use the crisp motion contract');
assert.doesNotMatch(guardian,/inset:14px -11px -15px 17px/,'Guardian depth plate must not overflow its card');
const upload=fs.readFileSync(path.join(web,'animation-upload-queue.html'),'utf8');
assert.match(upload,/escapeHtml\(f\.name\)/,'User-controlled file names must be output encoded before innerHTML rendering');
assert.match(upload,/Eclipse crisp motion contract/,'Upload Queue must use the crisp motion contract');
assert.match(upload,/\.file>\*\{min-width:0\}/,'Upload Queue rows must remain shrink-safe');
const progress=fs.readFileSync(path.join(web,'animation-ai-progress.html'),'utf8');
assert.match(progress,/Eclipse crisp motion contract/,'AI Progress must use the crisp motion contract');
assert.match(progress,/\.body>\*\{min-width:0\}/,'AI Progress columns must remain shrink-safe');
const otp=fs.readFileSync(path.join(web,'animation-otp-input.html'),'utf8');
assert.match(otp,/Eclipse crisp motion contract/,'Dark OTP must use the crisp motion contract');
const otpLight=fs.readFileSync(path.join(web,'animation-otp-light.html'),'utf8');
assert.match(otpLight,/Eclipse crisp motion contract/,'Light OTP must use the crisp motion contract');
for(const source of [upload,progress,otp,otpLight]){
  assert.match(source,/min-height:100dvh/,'Each demo must use the dynamic viewport height contract');
}
const page=fs.readFileSync(path.join(web,'animations.html'),'utf8');
const app=fs.readFileSync(path.join(web,'animation-lab.js'),'utf8');
const demoCatalog=fs.readFileSync(path.join(web,'animation-demos.js'),'utf8');
const css=fs.readFileSync(path.join(web,'animation-lab.css'),'utf8');
assert.match(page,/sandbox="allow-scripts"/,'Preview iframe must be sandboxed');
assert.doesNotMatch(page,/allow-same-origin|allow-forms|allow-popups/,'Preview sandbox must stay minimal');
assert.match(page,/Проверьте анимацию до внедрения/);
assert.match(page,/Компьютер/);
assert.match(page,/Параметры анимации/);
assert.match(page,/id="demo-search"/,'Animation search is required');
assert.match(page,/id="demo-filters"/,'Animation category filters are required');
assert.match(page,/animation-demos\.js\?v=8/,'Versioned demo catalog must load before the workbench');
assert.match(page,/id="demo-search"/,'Animation search is required');
assert.match(page,/id="demo-filters"/,'Animation category filters are required');
assert.match(page,/animation-demos\.js\?v=8/,'Versioned demo catalog must load before the workbench');
assert.match(page,/id="demo-search"/,'Animation search is required');
assert.match(page,/id="demo-filters"/,'Animation category filters are required');
assert.match(page,/animation-demos\.js\?v=8/,'Versioned demo catalog must load before the workbench');
assert.match(page,/id="demo-search"/,'Animation search is required');
assert.match(page,/id="demo-filters"/,'Animation category filters are required');
assert.match(page,/animation-demos\.js\?v=8/,'Versioned demo catalog must load before the workbench');
assert.match(page,/id="demo-search"/,'Animation search is required');
assert.match(page,/id="demo-filters"/,'Animation category filters are required');
assert.match(page,/animation-demos\.js\?v=8/,'Versioned demo catalog must load before the workbench');
assert.match(page,/id="demo-search"/,'Animation search is required');
assert.match(page,/id="demo-filters"/,'Animation category filters are required');
assert.match(page,/animation-demos\.js\?v=8/,'Versioned demo catalog must load before the workbench');
assert.doesNotMatch(css,/backdrop-filter:\s*blur|box-shadow:/i,'Animation Lab shell must stay crisp');
assert.match(page,/aria-label="Размер экрана"/);
assert.match(page,/id="export-dialog"/);
assert.match(app,/renderActive\(true\)/,'First animation must autoplay');
assert.match(app,/URLSearchParams/,'Workbench must generate deterministic preview URLs');
assert.match(app,/navigator\.clipboard/,'Export must support copy');
assert.match(app,/download/,'Export must support safe local download');
assert.match(css,/\.lab-shell\{grid-template-columns:minmax\(0,1fr\);width:100%\}/,'Mobile grid must not expand to the demo rail min-content width');
assert.match(css,/\.lab-shell>\*\{min-width:0\}/,'Workbench children must be allowed to shrink without horizontal overflow');
for(const demo of manifest.demos){assert.ok((app+demoCatalog).includes(demo.file),demo.file+' must be wired into the stage')}
const blade=fs.readFileSync(path.join(web,'animation-auth-blade.html'),'utf8');
assert.match(blade,/translateX/,'Auth blade must use a single horizontal translation');
assert.doesNotMatch(blade,/auth-blade[^}]*rotate/i,'Auth blade must never rotate');
const panda=fs.readFileSync(path.join(web,'animation-panda-lamp-login.html'),'utf8');
assert.match(panda,/data-gated[^>]*aria-hidden="true"[^>]*inert/,'Dark panda form must start outside the accessibility tree');
const safeUpload=fs.readFileSync(path.join(web,'animation-file-upload.html'),'utf8');
assert.match(safeUpload,/name\.textContent=file\.name/,'File names must be rendered with textContent');
const fly=fs.readFileSync(path.join(web,'animation-fly-to-cart.html'),'utf8');
assert.match(fly,/\.animate\(\[\{transform:/,'Fly-to-cart must use compositor transforms');
for(const demo of manifest.demos.slice(11)){
 const source=fs.readFileSync(path.join(web,demo.file),'utf8');
 assert.doesNotMatch(source,/\bfetch\s*\(|XMLHttpRequest|WebSocket|localStorage|sessionStorage/,'Product motion demos must not submit or persist data: '+demo.file);
 assert.doesNotMatch(source,/@keyframes[^}]*\{[^}]*(?:width|height|top|left|margin|padding|filter|box-shadow)\s*:/is,'Keyframes must stay compositor-only: '+demo.file);
}
console.log('Animation Lab checks passed for '+manifest.demos.length+' demos.');

assert.equal((app.match(/function visibleDemos\(\)/g)||[]).length,1,"visibleDemos must be declared once");
assert.match(app,/q\.set\("v","8"\)/,"Demo iframe URLs must carry the v8 cache key");
