const demos=[
{id:"upload-queue",title:"Upload Queue",label:"Очередь файлов",file:"animation-upload-queue.html",description:"Загрузка нескольких файлов с перетаскиванием, паузой, повтором, отменой, ошибкой сети и плавной перестановкой строк.",tags:["загрузка","очередь","восстановление"],states:["live","uploading","paused","error","complete"],readiness:"Готово к внедрению",project:"Eclipse Media"},
{id:"ai-progress",title:"AI Generation",label:"Этапы генерации",file:"animation-ai-progress.html",description:"Показывает подтверждённые этапы генерации, журнал событий, отмену, повтор и честно отделяет оценку времени от факта.",tags:["генерация","прогресс","журнал событий"],states:["live","preparing","generating","rendering","error","complete"],readiness:"Готово к внедрению",project:"AI Hub · Shotforge"},
{id:"otp-input",title:"OTP Auth Kit",label:"Проверка кода",file:"animation-otp-input.html",description:"Шесть полей кода поддерживают вставку, исправление, повторную отправку, проверку, ошибку и успешный вход с клавиатуры.",tags:["код входа","клавиатура","состояния"],states:["idle","typing","loading","error","success","expired"],readiness:"Готово к внедрению",project:"Eclipse Chat"},
{id:"reactive-login",title:"Guardian Login",label:"Реактивная форма",file:"animation-reactive-login.html",description:"Персонаж реагирует на курсор, закрывает глаза при вводе пароля и ясно показывает проверку, ошибку и успешный вход.",tags:["вход","обратная связь","персонаж"],states:["idle","loading","error","success"],readiness:"Нужен сервер",project:"Eclipse Chat"},
{id:"orbit-upload",title:"Orbit Upload",label:"Фазы обработки",file:"animation-orbit-upload.html",description:"Круговой индикатор последовательно показывает подготовку, передачу, обработку и готовность, сохраняя заметную отмену.",tags:["загрузка","обработка","статус"],states:["live","preparing","uploading","processing","complete","cancelled"],readiness:"Готово к внедрению",project:"Eclipse Media"},
{id:"vault-dial",title:"Vault Dial",label:"Механический замок",file:"animation-vault-dial.html",description:"Концепт защищённого входа с управлением мышью, колесом и клавиатурой. Механика выразительная, а текст остаётся неподвижным и резким.",tags:["безопасность","механика","концепт"],states:["idle","checking","error","complete"],readiness:"Концепт",project:"Sentinel"},
{id:"otp-light",title:"OTP Light",label:"Светлая проверка",file:"animation-otp-light.html",description:"Светлая версия проверки кода с теми же доступными состояниями, крупными целями касания и ясным результатом.",tags:["код входа","светлая тема","телефон"],states:["idle","typing","error","success"],readiness:"Готово к внедрению",project:"Eclipse Forge Landing"},
{id:"glass-navigation",title:"Clear Navigation",label:"Меню без размытия",file:"animation-glass-navigation.html",description:"Контрастное меню открывается кликом, управляется клавиатурой и безопасно закрывается при переходе или клике вне панели.",tags:["навигация","меню","клавиатура"],states:["idle","open","compact"],readiness:"Готово к внедрению",project:"Eclipse Library · Chat"},
{id:"hologram-cta",title:"Hologram CTA",label:"Призыв и окно",file:"animation-hologram-cta.html",description:"Контрастный призыв открывает доступное окно с удержанием фокуса, локальной проверкой формы и понятным успешным результатом.",tags:["призыв","окно","фокус"],states:["idle","open","success"],readiness:"Готово к внедрению",project:"Forge Landing · Growth OS"},
{id:"spatial-sidebar",title:"Spatial Sidebar",label:"Рабочая боковая панель",file:"animation-spatial-sidebar.html",description:"Рабочая боковая панель раскрывает разделы, показывает текущий пункт и переходит в компактный режим на узком экране.",tags:["боковая панель","разделы","рабочий интерфейс"],states:["idle","open","compact"],readiness:"Готово к внедрению",project:"Eclipse Chat · AI Hub"},
{id:"destination-card",title:"Destination Card",label:"Карточка направления",file:"animation-destination-card.html",description:"Карточка раскрывает подробности без перехода на другую страницу, сохраняя заметные действия для мыши, касания и клавиатуры.",tags:["карточка","адаптивность","раскрытие"],states:["idle","open","saved"],readiness:"Готово к внедрению",project:"Forge Landing · DnD Forge"}
];
const list=document.querySelector("#demo-list"),frame=document.querySelector("#stage-frame"),loading=document.querySelector("#stage-loading"),stage=document.querySelector("#motion-stage"),inspector=document.querySelector("#lab-inspector"),stateSelect=document.querySelector("#state-select"),speedSelect=document.querySelector("#speed-select"),timelineMode=document.querySelector("#timeline-mode"),timelineRange=document.querySelector("#timeline-range"),timelineOutput=document.querySelector("#timeline-output"),exportDialog=document.querySelector("#export-dialog"),exportCode=document.querySelector("#export-code"),exportHelp=document.querySelector("#export-help"),copyStatus=document.querySelector("#copy-status"),toggle=document.querySelector(".motion-toggle");
const controls={accent:document.querySelector("#accent-input"),glow:document.querySelector("#glow-input"),density:document.querySelector("#density-input"),accentOutput:document.querySelector("#accent-output"),glowOutput:document.querySelector("#glow-output"),densityOutput:document.querySelector("#density-output")};
const ui={index:document.querySelector("#active-index"),title:document.querySelector("#active-title"),description:document.querySelector("#active-description"),tags:document.querySelector("#active-tags"),file:document.querySelector("#stage-file"),open:[...document.querySelectorAll('[data-action="open"]')],download:[...document.querySelectorAll('[data-action="download"]')],readiness:document.querySelector("#readiness-value"),project:document.querySelector("#project-value"),status:document.querySelector("#stage-status")};
let active=0,frozen=false,exportTab="html",timelineTimer=0;
let settings={reduce:false,contrast:false,speed:1,accent:"#6ba3ff",glow:18,density:1,state:"live",time:0};
const densityLabels=["Плотно","Обычно","Свободно"];
const stateLabels={live:"Автодемо",idle:"Ожидание",uploading:"Загрузка",paused:"Пауза",error:"Ошибка",complete:"Готово",preparing:"Подготовка",generating:"Генерация",rendering:"Сборка",typing:"Ввод",loading:"Проверка",success:"Успех",expired:"Код истёк",processing:"Обработка",cancelled:"Отменено",checking:"Проверка",open:"Открыто",compact:"Компактно",saved:"Сохранено"};
function make(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}
function safeAccent(value){return /^#[0-9a-f]{6}$/i.test(value)?value:"#6ba3ff"}
function demoUrl(item,replay=false){const q=new URLSearchParams();if(settings.reduce)q.set("reduce","1");if(settings.contrast)q.set("contrast","1");if(settings.speed!==1)q.set("speed",String(settings.speed));if(settings.accent!=="#6ba3ff")q.set("accent",settings.accent);if(settings.glow!==18)q.set("glow",String(settings.glow/100));if(settings.density!==1)q.set("density",String(settings.density));if(settings.state!=="live")q.set("state",settings.state);if(frozen)q.set("t",String(settings.time));if(replay)q.set("replay",String(Date.now()));const query=q.toString();return item.file+(query?"?"+query:"")}
function renderList(){list.replaceChildren(...demos.map((item,index)=>{const button=make("button","demo-option");button.type="button";button.dataset.index=String(index);button.setAttribute("aria-current",String(index===active));button.append(make("span","demo-num",String(index+1).padStart(2,"0")));const copy=make("span","demo-copy");copy.append(make("b","",item.title),make("small","",item.label));const live=make("i","demo-live");live.setAttribute("aria-hidden","true");button.append(copy,live);return button}))}
function renderStates(){const item=demos[active];stateSelect.replaceChildren(...item.states.map(value=>{const option=document.createElement("option");option.value=value;option.textContent=stateLabels[value]||value;return option}));settings.state=item.states.includes(settings.state)?settings.state:item.states[0];stateSelect.value=settings.state}
function updateOutputs(){controls.accentOutput.value=settings.accent.toUpperCase();controls.glowOutput.value=settings.glow+"%";controls.densityOutput.value=densityLabels[settings.density];document.documentElement.style.setProperty("--accent",settings.accent);document.documentElement.classList.toggle("motion-reduced",settings.reduce);document.documentElement.classList.toggle("high-contrast",settings.contrast);toggle.setAttribute("aria-pressed",String(settings.reduce));toggle.querySelector("span:last-child").textContent=settings.reduce?"Анимация: уменьшена":"Анимация: полная";document.querySelector('[data-preference="reduce"]').setAttribute("aria-pressed",String(settings.reduce));document.querySelector('[data-preference="contrast"]').setAttribute("aria-pressed",String(settings.contrast))}
function loadFrame(replay=false){const item=demos[active];loading.hidden=false;frame.title="Интерактивное демо: "+item.title;frame.src=demoUrl(item,replay);ui.status.textContent=frozen?"КАДР "+settings.time.toFixed(1):"АКТИВНО"}
function refreshLinks(){const item=demos[active];ui.open.forEach(link=>link.href=demoUrl(item));ui.download.forEach(link=>link.href=item.file)}
function renderActive(replay=true){const item=demos[active];renderStates();ui.index.textContent=String(active+1).padStart(2,"0");ui.title.textContent=item.title;ui.description.textContent=item.description;ui.file.textContent=item.file;ui.readiness.textContent=item.readiness;ui.project.textContent=item.project;ui.tags.replaceChildren(...item.tags.map(tag=>make("li","",tag)));refreshLinks();renderList();loadFrame(replay);refreshExport()}
function select(index){active=index;settings.state=demos[index].states[0];frozen=false;settings.time=0;timelineMode.setAttribute("aria-pressed","false");timelineMode.textContent="Авто";timelineRange.disabled=true;timelineRange.value="0";timelineOutput.value="live";renderActive(true)}
function setFrozen(on){frozen=on;timelineMode.setAttribute("aria-pressed",String(on));timelineMode.textContent=on?"Кадр":"Авто";timelineRange.disabled=!on;timelineOutput.value=on?settings.time.toFixed(1)+"s":"live";loadFrame(true)}
function setPreference(key,value){settings[key]=value;updateOutputs();loadFrame(true);refreshLinks();refreshExport()}
function reactContract(item){const component=item.title.replace(/\s+/g,"");const states=item.states.filter(state=>state!=="live").map(state=>"'"+state+"'").join(" | ")||"'idle'";return ["type "+component+"State = "+states+";","","interface "+component+"Props {","  state: "+component+"State;","  reducedMotion?: boolean;","  onCancel?: () => void;","  onRetry?: () => void;","  onComplete?: () => void;","}","","// Port the state machine and visual tokens from "+item.file+".","// Keep API calls, auth and persistence outside the presentational component.","// Required QA: keyboard, touch, reduced motion, loading, error and success."].join("\n")}
function tokenContract(){return JSON.stringify({accent:settings.accent,glow:settings.glow,density:densityLabels[settings.density].toLowerCase(),speed:settings.speed,reducedMotion:settings.reduce,highContrast:settings.contrast,easing:"cubic-bezier(0.2, 0.8, 0.2, 1)",motionBudget:["transform","opacity"]},null,2)}
function qaContract(item){return ["# "+item.title+" — проверка перед внедрением","","- [ ] Главное действие понятно за 3 секунды","- [ ] Проверены состояния: "+item.states.map(state=>stateLabels[state]||state).join(", "),"- [ ] Работают клавиатура и заметный фокус","- [ ] Цели касания не меньше 44×44 px","- [ ] Уменьшение движения сохраняет полезную обратную связь","- [ ] При ширине 390 px нет горизонтальной прокрутки","- [ ] В каждом кадре меняются только transform и opacity","- [ ] Отмена и повтор не меняют production без подтверждения","- [ ] Серверная проверка и ограничения частоты реализуются отдельно"].join("\n")}
function refreshExport(){if(!exportDialog)return;const item=demos[active],values={html:["<!-- Download the complete standalone source: "+item.file+" -->","<iframe","  src=\""+demoUrl(item)+"\"","  title=\""+item.title+"\"","  sandbox=\"allow-scripts\"","\x3e</iframe>"].join("\n"),react:reactContract(item),tokens:tokenContract(),qa:qaContract(item)},helps={html:"Автономный файл открывается без build step и внешних зависимостей.",react:"State contract для переноса поведения в существующий React design system.",tokens:"Настройки текущего preview без secrets, runtime API и внешних действий.",qa:"Минимальный blocking checklist перед внедрением в продукт."};exportCode.textContent=values[exportTab];exportHelp.textContent=helps[exportTab]}
async function copyExport(){try{await navigator.clipboard.writeText(exportCode.textContent);copyStatus.textContent="Скопировано в буфер обмена"}catch{const selection=getSelection(),range=document.createRange();range.selectNodeContents(exportCode);selection.removeAllRanges();selection.addRange(range);copyStatus.textContent="Clipboard недоступен — код выделен для ручного копирования"}}
function reset(){settings={reduce:false,contrast:false,speed:1,accent:"#6ba3ff",glow:18,density:1,state:demos[active].states[0],time:0};controls.accent.value=settings.accent;controls.glow.value=String(settings.glow);controls.density.value=String(settings.density);speedSelect.value="1";frozen=false;timelineMode.setAttribute("aria-pressed","false");timelineMode.textContent="Авто";timelineRange.disabled=true;timelineRange.value="0";timelineOutput.value="live";updateOutputs();renderActive(true)}
list.addEventListener("click",event=>{const button=event.target.closest(".demo-option");if(button)select(Number(button.dataset.index))});
frame.addEventListener("load",()=>{loading.hidden=true});
document.querySelector('[data-action="replay"]').addEventListener("click",()=>loadFrame(true));
document.querySelector('[data-action="focus"]').addEventListener("click",event=>{document.documentElement.classList.toggle("focus-mode");event.currentTarget.textContent=document.documentElement.classList.contains("focus-mode")?"Выйти из фокуса":"Фокус-режим"});
document.querySelector('[data-action="reset"]').addEventListener("click",reset);
document.querySelector('[data-action="export"]').addEventListener("click",()=>{refreshExport();exportDialog.showModal()});
document.querySelector('[data-action="close-export"]').addEventListener("click",()=>exportDialog.close());
document.querySelector('[data-action="copy-export"]').addEventListener("click",copyExport);
exportDialog.addEventListener("click",event=>{if(event.target===exportDialog)exportDialog.close()});
document.querySelector(".export-tabs").addEventListener("click",event=>{const button=event.target.closest("[data-export-tab]");if(!button)return;exportTab=button.dataset.exportTab;document.querySelectorAll("[data-export-tab]").forEach(tab=>tab.setAttribute("aria-selected",String(tab===button)));copyStatus.textContent="";refreshExport()});
document.querySelectorAll("[data-viewport]").forEach(button=>button.addEventListener("click",()=>{stage.dataset.viewport=button.dataset.viewport;document.querySelectorAll("[data-viewport]").forEach(item=>item.setAttribute("aria-pressed",String(item===button)))}));
stateSelect.addEventListener("change",()=>{settings.state=stateSelect.value;loadFrame(true);refreshLinks();refreshExport()});
speedSelect.addEventListener("change",()=>{settings.speed=Number(speedSelect.value);loadFrame(true);refreshLinks();refreshExport()});
toggle.addEventListener("click",()=>setPreference("reduce",!settings.reduce));
document.querySelectorAll("[data-preference]").forEach(button=>button.addEventListener("click",()=>setPreference(button.dataset.preference,button.getAttribute("aria-pressed")!=="true")));
controls.accent.addEventListener("input",()=>{settings.accent=safeAccent(controls.accent.value);updateOutputs()});controls.accent.addEventListener("change",()=>{loadFrame(true);refreshLinks();refreshExport()});
controls.glow.addEventListener("input",()=>{settings.glow=Number(controls.glow.value);updateOutputs()});controls.glow.addEventListener("change",()=>{loadFrame(true);refreshLinks();refreshExport()});
controls.density.addEventListener("input",()=>{settings.density=Number(controls.density.value);updateOutputs();loadFrame(true);refreshLinks();refreshExport()});
timelineMode.addEventListener("click",()=>setFrozen(!frozen));
timelineRange.addEventListener("input",()=>{settings.time=Number(timelineRange.value);timelineOutput.value=settings.time.toFixed(1)+"s";clearTimeout(timelineTimer);timelineTimer=setTimeout(()=>loadFrame(false),80)});
document.querySelector(".inspect-toggle").addEventListener("click",event=>{const open=!inspector.classList.contains("is-open");inspector.classList.toggle("is-open",open);event.currentTarget.setAttribute("aria-expanded",String(open))});
document.addEventListener("keydown",event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="e"){event.preventDefault();refreshExport();exportDialog.showModal()}if(event.key==="Escape"&&document.documentElement.classList.contains("focus-mode")){document.documentElement.classList.remove("focus-mode");document.querySelector('[data-action="focus"]').textContent="Фокус-режим"}});
updateOutputs();renderList();renderActive(true);
