const demos=[
{id:"upload-queue",title:"Upload Queue",label:"Файлы и retry",file:"animation-upload-queue.html",description:"Пространственная file stack с drag & drop, pause, retry, cancel, simulated network error и FLIP reorder.",tags:["upload","3D stack","error recovery"],states:["live","uploading","paused","error","complete"],readiness:"Production ready",project:"Eclipse Media"},
{id:"ai-progress",title:"AI Generation",label:"Честный прогресс",file:"animation-ai-progress.html",description:"3D reactor показывает подтверждённые этапы генерации, live event log, cancel, retry и границу между оценкой и фактом.",tags:["AI","3D reactor","progress"],states:["live","preparing","generating","rendering","error","complete"],readiness:"Production ready",project:"AI Hub · Shotforge"},
{id:"otp-input",title:"OTP Auth Kit",label:"Проверка входа",file:"animation-otp-input.html",description:"Шесть spatial code cells поддерживают paste, edit, resend timer, loading, error shake и success без ловушек клавиатуры.",tags:["OTP","spatial input","keyboard"],states:["idle","typing","loading","error","success","expired"],readiness:"Production ready",project:"Eclipse Chat"},
{id:"reactive-login",title:"Guardian Login",label:"Реактивный вход",file:"animation-reactive-login.html",description:"Layered 3D guardian следует за курсором, закрывает глаза на password и показывает loading/error/success.",tags:["auth","3D companion","feedback"],states:["idle","loading","error","success"],readiness:"Needs backend",project:"Eclipse Chat"},
{id:"orbit-upload",title:"Orbit Upload",label:"Фазы обработки",file:"animation-orbit-upload.html",description:"3D transfer portal объясняет preparing, transfer, processing, ready и оставляет явную отмену.",tags:["upload","3D portal","status"],states:["live","preparing","uploading","processing","complete","cancelled"],readiness:"Production ready",project:"Eclipse Media"},
{id:"vault-dial",title:"Vault Dial",label:"Security concept",file:"animation-vault-dial.html",description:"Объёмный security concept с drag, wheel, keyboard, 3D parallax и механическим unlock. Не заменяет обычную auth.",tags:["security","3D dial","concept"],states:["idle","checking","error","complete"],readiness:"Concept only",project:"Sentinel"},
{id:"otp-light",title:"OTP Glass",label:"Светлый вариант",file:"animation-otp-light.html",description:"Светлая translucent 3D OTP-композиция с тем же доступным mobile-first auth contract.",tags:["OTP","glass depth","mobile"],states:["idle","typing","error","success"],readiness:"Production ready",project:"Eclipse Forge Landing"},
{id:"glass-navigation",title:"Glass Navigation",label:"Меню с глубиной",file:"animation-glass-navigation.html",description:"Click-first glass navigation с объёмным dropdown, keyboard управлением и безопасным закрытием вне меню.",tags:["navigation","glass depth","keyboard"],states:["idle","open","compact"],readiness:"Production ready",project:"Eclipse Library · Chat"},
{id:"hologram-cta",title:"Hologram CTA",label:"CTA и modal",file:"animation-hologram-cta.html",description:"Пространственный footer CTA открывает доступный dialog с focus trap, локальной валидацией и success state.",tags:["CTA","modal","focus management"],states:["idle","open","success"],readiness:"Production ready",project:"Forge Landing · Growth OS"},
{id:"spatial-sidebar",title:"Spatial Sidebar",label:"Раскрываемые разделы",file:"animation-spatial-sidebar.html",description:"Полупрозрачный operational sidebar с accordion-разделами, активным состоянием и компактным mobile режимом.",tags:["sidebar","accordion","operational UI"],states:["idle","open","compact"],readiness:"Production ready",project:"Eclipse Chat · AI Hub"},
{id:"destination-card",title:"Destination Card",label:"Адаптивная карточка",file:"animation-destination-card.html",description:"Карточка раскрывает детали через мягкий spatial transition, сохраняя понятный CTA, touch и keyboard управление.",tags:["card","responsive","3D reveal"],states:["idle","open","saved"],readiness:"Production ready",project:"Forge Landing · DnD Forge"}
];
const list=document.querySelector("#demo-list"),frame=document.querySelector("#stage-frame"),loading=document.querySelector("#stage-loading"),stage=document.querySelector("#motion-stage"),inspector=document.querySelector("#lab-inspector"),stateSelect=document.querySelector("#state-select"),speedSelect=document.querySelector("#speed-select"),timelineMode=document.querySelector("#timeline-mode"),timelineRange=document.querySelector("#timeline-range"),timelineOutput=document.querySelector("#timeline-output"),exportDialog=document.querySelector("#export-dialog"),exportCode=document.querySelector("#export-code"),exportHelp=document.querySelector("#export-help"),copyStatus=document.querySelector("#copy-status"),toggle=document.querySelector(".motion-toggle");
const controls={accent:document.querySelector("#accent-input"),glow:document.querySelector("#glow-input"),density:document.querySelector("#density-input"),accentOutput:document.querySelector("#accent-output"),glowOutput:document.querySelector("#glow-output"),densityOutput:document.querySelector("#density-output")};
const ui={index:document.querySelector("#active-index"),title:document.querySelector("#active-title"),description:document.querySelector("#active-description"),tags:document.querySelector("#active-tags"),file:document.querySelector("#stage-file"),open:[...document.querySelectorAll('[data-action="open"]')],download:[...document.querySelectorAll('[data-action="download"]')],readiness:document.querySelector("#readiness-value"),project:document.querySelector("#project-value"),status:document.querySelector("#stage-status")};
let active=0,frozen=false,exportTab="html",timelineTimer=0;
let settings={reduce:false,contrast:false,speed:1,accent:"#6ba3ff",glow:55,density:1,state:"live",time:0};
const densityLabels=["Compact","Comfortable","Spacious"];
function make(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}
function safeAccent(value){return /^#[0-9a-f]{6}$/i.test(value)?value:"#6ba3ff"}
function demoUrl(item,replay=false){const q=new URLSearchParams();if(settings.reduce)q.set("reduce","1");if(settings.contrast)q.set("contrast","1");if(settings.speed!==1)q.set("speed",String(settings.speed));if(settings.accent!=="#6ba3ff")q.set("accent",settings.accent);if(settings.glow!==55)q.set("glow",String(settings.glow/100));if(settings.density!==1)q.set("density",String(settings.density));if(settings.state!=="live")q.set("state",settings.state);if(frozen)q.set("t",String(settings.time));if(replay)q.set("replay",String(Date.now()));const query=q.toString();return item.file+(query?"?"+query:"")}
function renderList(){list.replaceChildren(...demos.map((item,index)=>{const button=make("button","demo-option");button.type="button";button.dataset.index=String(index);button.setAttribute("aria-current",String(index===active));button.append(make("span","demo-num",String(index+1).padStart(2,"0")));const copy=make("span","demo-copy");copy.append(make("b","",item.title),make("small","",item.label));const live=make("i","demo-live");live.setAttribute("aria-hidden","true");button.append(copy,live);return button}))}
function renderStates(){const item=demos[active];stateSelect.replaceChildren(...item.states.map(value=>{const option=document.createElement("option");option.value=value;option.textContent=value==="live"?"Auto demo":value[0].toUpperCase()+value.slice(1);return option}));settings.state=item.states.includes(settings.state)?settings.state:item.states[0];stateSelect.value=settings.state}
function updateOutputs(){controls.accentOutput.value=settings.accent.toUpperCase();controls.glowOutput.value=settings.glow+"%";controls.densityOutput.value=densityLabels[settings.density];document.documentElement.style.setProperty("--accent",settings.accent);document.documentElement.classList.toggle("motion-reduced",settings.reduce);document.documentElement.classList.toggle("high-contrast",settings.contrast);toggle.setAttribute("aria-pressed",String(settings.reduce));toggle.querySelector("span:last-child").textContent=settings.reduce?"Motion: reduced":"Motion: full";document.querySelector('[data-preference="reduce"]').setAttribute("aria-pressed",String(settings.reduce));document.querySelector('[data-preference="contrast"]').setAttribute("aria-pressed",String(settings.contrast))}
function loadFrame(replay=false){const item=demos[active];loading.hidden=false;frame.title="Интерактивное демо: "+item.title;frame.src=demoUrl(item,replay);ui.status.textContent=frozen?"FRAME "+settings.time.toFixed(1):"LIVE"}
function refreshLinks(){const item=demos[active];ui.open.forEach(link=>link.href=demoUrl(item));ui.download.forEach(link=>link.href=item.file)}
function renderActive(replay=true){const item=demos[active];renderStates();ui.index.textContent=String(active+1).padStart(2,"0");ui.title.textContent=item.title;ui.description.textContent=item.description;ui.file.textContent=item.file;ui.readiness.textContent=item.readiness;ui.project.textContent=item.project;ui.tags.replaceChildren(...item.tags.map(tag=>make("li","",tag)));refreshLinks();renderList();loadFrame(replay);refreshExport()}
function select(index){active=index;settings.state=demos[index].states[0];frozen=false;settings.time=0;timelineMode.setAttribute("aria-pressed","false");timelineMode.textContent="Live";timelineRange.disabled=true;timelineRange.value="0";timelineOutput.value="live";renderActive(true)}
function setFrozen(on){frozen=on;timelineMode.setAttribute("aria-pressed",String(on));timelineMode.textContent=on?"Frame":"Live";timelineRange.disabled=!on;timelineOutput.value=on?settings.time.toFixed(1)+"s":"live";loadFrame(true)}
function setPreference(key,value){settings[key]=value;updateOutputs();loadFrame(true);refreshLinks();refreshExport()}
function reactContract(item){const component=item.title.replace(/\s+/g,"");const states=item.states.filter(state=>state!=="live").map(state=>"'"+state+"'").join(" | ")||"'idle'";return ["type "+component+"State = "+states+";","","interface "+component+"Props {","  state: "+component+"State;","  reducedMotion?: boolean;","  onCancel?: () => void;","  onRetry?: () => void;","  onComplete?: () => void;","}","","// Port the state machine and visual tokens from "+item.file+".","// Keep API calls, auth and persistence outside the presentational component.","// Required QA: keyboard, touch, reduced motion, loading, error and success."].join("\n")}
function tokenContract(){return JSON.stringify({accent:settings.accent,glow:settings.glow,density:densityLabels[settings.density].toLowerCase(),speed:settings.speed,reducedMotion:settings.reduce,highContrast:settings.contrast,easing:"cubic-bezier(0.2, 0.8, 0.2, 1)",motionBudget:["transform","opacity"]},null,2)}
function qaContract(item){return ["# "+item.title+" — ship checklist","","- [ ] Main action is obvious in 3 seconds","- [ ] States checked: "+item.states.join(", "),"- [ ] Keyboard and visible focus tested","- [ ] Touch target is at least 44×44 px","- [ ] Reduced motion keeps useful feedback","- [ ] No horizontal overflow at 390 px","- [ ] No per-frame layout or paint animation","- [ ] Cancel/retry cannot mutate production without approval","- [ ] Backend validation and rate limits are implemented separately"].join("\n")}
function refreshExport(){if(!exportDialog)return;const item=demos[active],values={html:["<!-- Download the complete standalone source: "+item.file+" -->","<iframe","  src=\""+demoUrl(item)+"\"","  title=\""+item.title+"\"","  sandbox=\"allow-scripts\"","\x3e</iframe>"].join("\n"),react:reactContract(item),tokens:tokenContract(),qa:qaContract(item)},helps={html:"Автономный файл открывается без build step и внешних зависимостей.",react:"State contract для переноса поведения в существующий React design system.",tokens:"Настройки текущего preview без secrets, runtime API и внешних действий.",qa:"Минимальный blocking checklist перед внедрением в продукт."};exportCode.textContent=values[exportTab];exportHelp.textContent=helps[exportTab]}
async function copyExport(){try{await navigator.clipboard.writeText(exportCode.textContent);copyStatus.textContent="Скопировано в буфер обмена"}catch{const selection=getSelection(),range=document.createRange();range.selectNodeContents(exportCode);selection.removeAllRanges();selection.addRange(range);copyStatus.textContent="Clipboard недоступен — код выделен для ручного копирования"}}
function reset(){settings={reduce:false,contrast:false,speed:1,accent:"#6ba3ff",glow:55,density:1,state:demos[active].states[0],time:0};controls.accent.value=settings.accent;controls.glow.value=String(settings.glow);controls.density.value=String(settings.density);speedSelect.value="1";frozen=false;timelineMode.setAttribute("aria-pressed","false");timelineMode.textContent="Live";timelineRange.disabled=true;timelineRange.value="0";timelineOutput.value="live";updateOutputs();renderActive(true)}
list.addEventListener("click",event=>{const button=event.target.closest(".demo-option");if(button)select(Number(button.dataset.index))});
frame.addEventListener("load",()=>{loading.hidden=true});
document.querySelector('[data-action="replay"]').addEventListener("click",()=>loadFrame(true));
document.querySelector('[data-action="focus"]').addEventListener("click",event=>{document.documentElement.classList.toggle("focus-mode");event.currentTarget.textContent=document.documentElement.classList.contains("focus-mode")?"Выйти из фокуса":"Фокус-режим"});
document.querySelector('[data-action="reset"]').addEventListener("click",reset);
document.querySelector('[data-action="export"]').addEventListener("click",()=>{refreshExport();exportDialog.showModal()});
document.querySelector('[data-action="close-export"]').addEventListener("click",()=>exportDialog.close());
document.querySelector('[data-action="copy-export"]').addEventListener("click",copyExport);
exportDialog.addEventListener("click",event=>{if(event.target===exportDialog)exportDialog.close()});
document.querySelector(".export-tabs").addEventListener("click",event=>{const button=event.target.closest("[data-export-tab]");if(!button)return;exportTab=button.dataset.exportTab;document.querySelectorAll("[data-export-tab]").forEach(tab=>tab.setAttribute("aria-selected",String(tab===button)));copyStatus.textContent="";refreshExport()});
document.querySelectorAll("[data-viewport]").forEach(button=>button.addEventListener("click",()=>{stage.dataset.viewport=button.dataset.viewport;document.querySelectorAll("[data-viewport]").forEach(item=>item.setAttribute("aria-pressed",String(item===button)))}));
stateSelect.addEventListener("change",()=>{settings.state=stateSelect.value;loadFrame(true);refreshLinks();refreshExport()});
speedSelect.addEventListener("change",()=>{settings.speed=Number(speedSelect.value);loadFrame(true);refreshLinks();refreshExport()});
toggle.addEventListener("click",()=>setPreference("reduce",!settings.reduce));
document.querySelectorAll("[data-preference]").forEach(button=>button.addEventListener("click",()=>setPreference(button.dataset.preference,button.getAttribute("aria-pressed")!=="true")));
controls.accent.addEventListener("input",()=>{settings.accent=safeAccent(controls.accent.value);updateOutputs()});controls.accent.addEventListener("change",()=>{loadFrame(true);refreshLinks();refreshExport()});
controls.glow.addEventListener("input",()=>{settings.glow=Number(controls.glow.value);updateOutputs()});controls.glow.addEventListener("change",()=>{loadFrame(true);refreshLinks();refreshExport()});
controls.density.addEventListener("input",()=>{settings.density=Number(controls.density.value);updateOutputs();loadFrame(true);refreshLinks();refreshExport()});
timelineMode.addEventListener("click",()=>setFrozen(!frozen));
timelineRange.addEventListener("input",()=>{settings.time=Number(timelineRange.value);timelineOutput.value=settings.time.toFixed(1)+"s";clearTimeout(timelineTimer);timelineTimer=setTimeout(()=>loadFrame(false),80)});
document.querySelector(".inspect-toggle").addEventListener("click",event=>{const open=!inspector.classList.contains("is-open");inspector.classList.toggle("is-open",open);event.currentTarget.setAttribute("aria-expanded",String(open))});
document.addEventListener("keydown",event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="e"){event.preventDefault();refreshExport();exportDialog.showModal()}if(event.key==="Escape"&&document.documentElement.classList.contains("focus-mode")){document.documentElement.classList.remove("focus-mode");document.querySelector('[data-action="focus"]').textContent="Фокус-режим"}});
updateOutputs();renderList();renderActive(true);
